// Copyright 2025 Stoolap Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! STARK proof types for zero-knowledge proofs
//!
//! This module provides data structures for STARK proofs generated by STWO.

use crate::zk::cairo::CairoProgramHash;

/// Maximum size of a STARK proof in bytes (500 KB)
pub const MAX_PROOF_SIZE: usize = 500 * 1024;

/// Maximum size of public inputs in bytes (100 KB)
pub const MAX_PUBLIC_INPUTS_SIZE: usize = 100 * 1024;

/// Maximum size of inputs/outputs in bytes (10 KB each)
pub const MAX_INPUTS_SIZE: usize = 10 * 1024;
pub const MAX_OUTPUTS_SIZE: usize = 10 * 1024;

/// STARK proof generated by STWO prover
///
/// Contains all data needed to verify a Cairo program execution
/// using the STWO verifier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StarkProof {
    /// Blake3 hash of the Cairo program that generated this proof
    pub program_hash: CairoProgramHash,
    /// Private inputs for the program execution
    pub inputs: Vec<u8>,
    /// Outputs from the program execution
    pub outputs: Vec<u8>,
    /// Raw STARK proof bytes from STWO prover
    pub proof: Vec<u8>,
    /// Public inputs needed for verification
    pub public_inputs: Vec<u8>,
}

impl StarkProof {
    /// Create a new STARK proof
    pub fn new(
        program_hash: CairoProgramHash,
        inputs: Vec<u8>,
        outputs: Vec<u8>,
        proof: Vec<u8>,
        public_inputs: Vec<u8>,
    ) -> Self {
        Self {
            program_hash,
            inputs,
            outputs,
            proof,
            public_inputs,
        }
    }

    /// Get the total size of this proof in bytes
    pub fn size(&self) -> usize {
        self.inputs.len() + self.outputs.len() + self.proof.len() + self.public_inputs.len()
    }

    /// Check if this proof is within size limits
    pub fn is_valid_size(&self) -> bool {
        !self.proof.is_empty()
            && self.inputs.len() <= MAX_INPUTS_SIZE
            && self.outputs.len() <= MAX_OUTPUTS_SIZE
            && self.proof.len() <= MAX_PROOF_SIZE
            && self.public_inputs.len() <= MAX_PUBLIC_INPUTS_SIZE
    }

    /// Validate the proof structure
    pub fn validate(&self) -> Result<(), ProofValidationError> {
        if self.inputs.len() > MAX_INPUTS_SIZE {
            return Err(ProofValidationError::InputsTooLarge(self.inputs.len()));
        }
        if self.outputs.len() > MAX_OUTPUTS_SIZE {
            return Err(ProofValidationError::OutputsTooLarge(self.outputs.len()));
        }
        if self.proof.len() > MAX_PROOF_SIZE {
            return Err(ProofValidationError::ProofTooLarge(self.proof.len()));
        }
        if self.public_inputs.len() > MAX_PUBLIC_INPUTS_SIZE {
            return Err(ProofValidationError::PublicInputsTooLarge(
                self.public_inputs.len(),
            ));
        }
        if self.proof.is_empty() {
            return Err(ProofValidationError::EmptyProof);
        }
        Ok(())
    }

    /// Get a summary of the proof for logging/debugging
    pub fn summary(&self) -> ProofSummary {
        ProofSummary {
            program_hash: self.program_hash,
            inputs_size: self.inputs.len(),
            outputs_size: self.outputs.len(),
            proof_size: self.proof.len(),
            public_inputs_size: self.public_inputs.len(),
            total_size: self.size(),
        }
    }
}

/// STARK proof validation error
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProofValidationError {
    /// Inputs exceed maximum size
    InputsTooLarge(usize),
    /// Outputs exceed maximum size
    OutputsTooLarge(usize),
    /// Proof exceeds maximum size
    ProofTooLarge(usize),
    /// Public inputs exceed maximum size
    PublicInputsTooLarge(usize),
    /// Proof is empty
    EmptyProof,
}

impl std::fmt::Display for ProofValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProofValidationError::InputsTooLarge(size) => {
                write!(
                    f,
                    "Inputs too large: {} bytes (max {})",
                    size, MAX_INPUTS_SIZE
                )
            }
            ProofValidationError::OutputsTooLarge(size) => {
                write!(
                    f,
                    "Outputs too large: {} bytes (max {})",
                    size, MAX_OUTPUTS_SIZE
                )
            }
            ProofValidationError::ProofTooLarge(size) => {
                write!(
                    f,
                    "Proof too large: {} bytes (max {})",
                    size, MAX_PROOF_SIZE
                )
            }
            ProofValidationError::PublicInputsTooLarge(size) => write!(
                f,
                "Public inputs too large: {} bytes (max {})",
                size, MAX_PUBLIC_INPUTS_SIZE
            ),
            ProofValidationError::EmptyProof => write!(f, "Proof cannot be empty"),
        }
    }
}

impl std::error::Error for ProofValidationError {}

/// Summary of a STARK proof for debugging
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProofSummary {
    /// Program hash
    pub program_hash: CairoProgramHash,
    /// Size of inputs in bytes
    pub inputs_size: usize,
    /// Size of outputs in bytes
    pub outputs_size: usize,
    /// Size of proof in bytes
    pub proof_size: usize,
    /// Size of public inputs in bytes
    pub public_inputs_size: usize,
    /// Total size in bytes
    pub total_size: usize,
}

/// Zero-knowledge operation variants
///
/// These operations can be submitted to the blockchain
/// to interact with ZK proof functionality.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ZKOperation {
    /// Submit a STARK proof for verification
    SubmitProof {
        /// The proof to submit
        proof: StarkProof,
        /// Gas limit for verification
        gas_limit: u64,
    },

    /// Register a new Cairo program
    RegisterProgram {
        /// The program to register
        program: CairoProgramForRegistration,
    },

    /// Verify a STARK proof (read-only operation)
    VerifyProof {
        /// The proof to verify
        proof: StarkProof,
    },
}

/// Cairo program data for registration
///
/// This is a simplified version of CairoProgram containing
/// only the data needed for on-chain registration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CairoProgramForRegistration {
    /// Blake3 hash of the program
    pub hash: CairoProgramHash,
    /// Cairo source code
    pub source: String,
    /// Compiler version
    pub version: u32,
}

impl From<crate::zk::cairo::CairoProgram> for CairoProgramForRegistration {
    fn from(program: crate::zk::cairo::CairoProgram) -> Self {
        Self {
            hash: program.hash,
            source: program.source,
            version: program.version,
        }
    }
}

/// Solana-style serialization for STARK proofs
///
/// This trait provides binary serialization compatible with Solana's
/// zero-copy read format.
pub trait SolanaSerialize: Sized {
    /// Serialize to bytes
    fn serialize(&self) -> Vec<u8>;

    /// Deserialize from bytes
    fn deserialize(data: &[u8]) -> Result<Self, SerializationError>;

    /// Get the serialized size
    fn serialized_size(&self) -> usize;
}

/// Serialization error
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SerializationError {
    /// Invalid data format
    InvalidFormat(String),
    /// Data too short
    DataTooShort,
    /// Data too long
    DataTooLong,
    /// Invalid length prefix
    InvalidLength,
}

impl std::fmt::Display for SerializationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SerializationError::InvalidFormat(msg) => write!(f, "Invalid format: {}", msg),
            SerializationError::DataTooShort => write!(f, "Data too short"),
            SerializationError::DataTooLong => write!(f, "Data too long"),
            SerializationError::InvalidLength => write!(f, "Invalid length prefix"),
        }
    }
}

impl std::error::Error for SerializationError {}

impl SolanaSerialize for StarkProof {
    fn serialize(&self) -> Vec<u8> {
        let mut buffer = Vec::new();

        // Write program_hash (32 bytes)
        buffer.extend_from_slice(&self.program_hash);

        // Write inputs_len (4 bytes, little-endian)
        let inputs_len = self.inputs.len() as u32;
        buffer.extend_from_slice(&inputs_len.to_le_bytes());

        // Write inputs
        buffer.extend_from_slice(&self.inputs);

        // Write outputs_len (4 bytes, little-endian)
        let outputs_len = self.outputs.len() as u32;
        buffer.extend_from_slice(&outputs_len.to_le_bytes());

        // Write outputs
        buffer.extend_from_slice(&self.outputs);

        // Write proof_len (4 bytes, little-endian)
        let proof_len = self.proof.len() as u32;
        buffer.extend_from_slice(&proof_len.to_le_bytes());

        // Write proof
        buffer.extend_from_slice(&self.proof);

        // Write public_inputs_len (4 bytes, little-endian)
        let public_inputs_len = self.public_inputs.len() as u32;
        buffer.extend_from_slice(&public_inputs_len.to_le_bytes());

        // Write public_inputs
        buffer.extend_from_slice(&self.public_inputs);

        buffer
    }

    fn deserialize(data: &[u8]) -> Result<Self, SerializationError> {
        let mut pos = 0;

        // Read program_hash (32 bytes)
        if data.len() < 32 {
            return Err(SerializationError::DataTooShort);
        }
        let mut program_hash = [0u8; 32];
        program_hash.copy_from_slice(&data[pos..pos + 32]);
        pos += 32;

        // Read inputs_len (4 bytes)
        if data.len() < pos + 4 {
            return Err(SerializationError::DataTooShort);
        }
        let inputs_len = u32::from_le_bytes(data[pos..pos + 4].try_into().unwrap()) as usize;
        pos += 4;

        // Read inputs
        if data.len() < pos + inputs_len {
            return Err(SerializationError::DataTooShort);
        }
        let inputs = data[pos..pos + inputs_len].to_vec();
        pos += inputs_len;

        // Read outputs_len (4 bytes)
        if data.len() < pos + 4 {
            return Err(SerializationError::DataTooShort);
        }
        let outputs_len = u32::from_le_bytes(data[pos..pos + 4].try_into().unwrap()) as usize;
        pos += 4;

        // Read outputs
        if data.len() < pos + outputs_len {
            return Err(SerializationError::DataTooShort);
        }
        let outputs = data[pos..pos + outputs_len].to_vec();
        pos += outputs_len;

        // Read proof_len (4 bytes)
        if data.len() < pos + 4 {
            return Err(SerializationError::DataTooShort);
        }
        let proof_len = u32::from_le_bytes(data[pos..pos + 4].try_into().unwrap()) as usize;
        pos += 4;

        // Read proof
        if data.len() < pos + proof_len {
            return Err(SerializationError::DataTooShort);
        }
        let proof = data[pos..pos + proof_len].to_vec();
        pos += proof_len;

        // Read public_inputs_len (4 bytes)
        if data.len() < pos + 4 {
            return Err(SerializationError::DataTooShort);
        }
        let public_inputs_len = u32::from_le_bytes(data[pos..pos + 4].try_into().unwrap()) as usize;
        pos += 4;

        // Read public_inputs
        if data.len() < pos + public_inputs_len {
            return Err(SerializationError::DataTooShort);
        }
        let public_inputs = data[pos..pos + public_inputs_len].to_vec();

        Ok(StarkProof {
            program_hash,
            inputs,
            outputs,
            proof,
            public_inputs,
        })
    }

    fn serialized_size(&self) -> usize {
        32 + // program_hash
        4 + self.inputs.len() + // inputs_len + inputs
        4 + self.outputs.len() + // outputs_len + outputs
        4 + self.proof.len() + // proof_len + proof
        4 + self.public_inputs.len() // public_inputs_len + public_inputs
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stark_proof_creation() {
        let program_hash = [1u8; 32];
        let inputs = vec![1, 2, 3];
        let outputs = vec![4, 5, 6];
        let proof = vec![7, 8, 9];
        let public_inputs = vec![10, 11, 12];

        let stark_proof = StarkProof::new(
            program_hash,
            inputs.clone(),
            outputs.clone(),
            proof.clone(),
            public_inputs.clone(),
        );

        assert_eq!(stark_proof.program_hash, program_hash);
        assert_eq!(stark_proof.inputs, inputs);
        assert_eq!(stark_proof.outputs, outputs);
        assert_eq!(stark_proof.proof, proof);
        assert_eq!(stark_proof.public_inputs, public_inputs);
    }

    #[test]
    fn test_stark_proof_size() {
        let proof = StarkProof::new(
            [0u8; 32],
            vec![1; 100],
            vec![2; 200],
            vec![3; 300],
            vec![4; 400],
        );

        assert_eq!(proof.size(), 100 + 200 + 300 + 400);
    }

    #[test]
    fn test_stark_proof_valid_size() {
        let valid_proof = StarkProof::new(
            [0u8; 32],
            vec![1; 100],
            vec![2; 100],
            vec![3; 100],
            vec![4; 100],
        );

        assert!(valid_proof.is_valid_size());
        assert!(valid_proof.validate().is_ok());
    }

    #[test]
    fn test_stark_proof_invalid_size_inputs() {
        let invalid_proof = StarkProof::new(
            [0u8; 32],
            vec![1; MAX_INPUTS_SIZE + 1],
            vec![2; 100],
            vec![3; 100],
            vec![4; 100],
        );

        assert!(!invalid_proof.is_valid_size());
        match invalid_proof.validate() {
            Err(ProofValidationError::InputsTooLarge(_)) => {}
            _ => panic!("Expected InputsTooLarge error"),
        }
    }

    #[test]
    fn test_stark_proof_invalid_size_outputs() {
        let invalid_proof = StarkProof::new(
            [0u8; 32],
            vec![1; 100],
            vec![2; MAX_OUTPUTS_SIZE + 1],
            vec![3; 100],
            vec![4; 100],
        );

        assert!(!invalid_proof.is_valid_size());
        match invalid_proof.validate() {
            Err(ProofValidationError::OutputsTooLarge(_)) => {}
            _ => panic!("Expected OutputsTooLarge error"),
        }
    }

    #[test]
    fn test_stark_proof_invalid_size_proof() {
        let invalid_proof = StarkProof::new(
            [0u8; 32],
            vec![1; 100],
            vec![2; 100],
            vec![3; MAX_PROOF_SIZE + 1],
            vec![4; 100],
        );

        assert!(!invalid_proof.is_valid_size());
        match invalid_proof.validate() {
            Err(ProofValidationError::ProofTooLarge(_)) => {}
            _ => panic!("Expected ProofTooLarge error"),
        }
    }

    #[test]
    fn test_stark_proof_invalid_size_public_inputs() {
        let invalid_proof = StarkProof::new(
            [0u8; 32],
            vec![1; 100],
            vec![2; 100],
            vec![3; 100],
            vec![4; MAX_PUBLIC_INPUTS_SIZE + 1],
        );

        assert!(!invalid_proof.is_valid_size());
        match invalid_proof.validate() {
            Err(ProofValidationError::PublicInputsTooLarge(_)) => {}
            _ => panic!("Expected PublicInputsTooLarge error"),
        }
    }

    #[test]
    fn test_stark_proof_empty_proof() {
        let invalid_proof = StarkProof::new([0u8; 32], vec![], vec![], vec![], vec![]);

        assert!(!invalid_proof.is_valid_size());
        match invalid_proof.validate() {
            Err(ProofValidationError::EmptyProof) => {}
            _ => panic!("Expected EmptyProof error"),
        }
    }

    #[test]
    fn test_proof_summary() {
        let proof = StarkProof::new(
            [42u8; 32],
            vec![1; 100],
            vec![2; 200],
            vec![3; 300],
            vec![4; 400],
        );

        let summary = proof.summary();
        assert_eq!(summary.program_hash, [42u8; 32]);
        assert_eq!(summary.inputs_size, 100);
        assert_eq!(summary.outputs_size, 200);
        assert_eq!(summary.proof_size, 300);
        assert_eq!(summary.public_inputs_size, 400);
        assert_eq!(summary.total_size, 1000);
    }

    #[test]
    fn test_zk_operation_submit_proof() {
        let proof = StarkProof::new([0u8; 32], vec![1], vec![2], vec![3], vec![4]);
        let op = ZKOperation::SubmitProof {
            proof: proof.clone(),
            gas_limit: 100000,
        };

        match op {
            ZKOperation::SubmitProof {
                proof: p,
                gas_limit,
            } => {
                assert_eq!(p, proof);
                assert_eq!(gas_limit, 100000);
            }
            _ => panic!("Expected SubmitProof variant"),
        }
    }

    #[test]
    fn test_zk_operation_verify_proof() {
        let proof = StarkProof::new([0u8; 32], vec![1], vec![2], vec![3], vec![4]);
        let op = ZKOperation::VerifyProof {
            proof: proof.clone(),
        };

        match op {
            ZKOperation::VerifyProof { proof: p } => {
                assert_eq!(p, proof);
            }
            _ => panic!("Expected VerifyProof variant"),
        }
    }

    #[test]
    fn test_zk_operation_register_program() {
        let program = CairoProgramForRegistration {
            hash: [5u8; 32],
            source: "fn main() {}".to_string(),
            version: 2,
        };
        let op = ZKOperation::RegisterProgram {
            program: program.clone(),
        };

        match op {
            ZKOperation::RegisterProgram { program: p } => {
                assert_eq!(p.hash, program.hash);
                assert_eq!(p.source, program.source);
                assert_eq!(p.version, program.version);
            }
            _ => panic!("Expected RegisterProgram variant"),
        }
    }

    #[test]
    fn test_stark_proof_serialize_roundtrip() {
        let original = StarkProof::new(
            [1u8; 32],
            vec![1, 2, 3],
            vec![4, 5, 6],
            vec![7, 8, 9],
            vec![10, 11, 12],
        );

        let serialized = original.serialize();
        let deserialized = StarkProof::deserialize(&serialized).unwrap();

        assert_eq!(deserialized, original);
    }

    #[test]
    fn test_stark_proof_serialize_empty_data() {
        let proof = StarkProof::new([1u8; 32], vec![], vec![], vec![1, 2, 3], vec![]);
        let serialized = proof.serialize();

        // Should have: program_hash (32) + inputs_len (4) + inputs (0) +
        //              outputs_len (4) + outputs (0) + proof_len (4) + proof (3) +
        //              public_inputs_len (4) + public_inputs (0)
        assert_eq!(serialized.len(), 32 + 4 + 4 + 4 + 3 + 4);

        let deserialized = StarkProof::deserialize(&serialized).unwrap();
        assert_eq!(deserialized.proof, vec![1, 2, 3]);
    }

    #[test]
    fn test_stark_proof_serialize_large_data() {
        let large_data = vec![42u8; 1000];
        let proof = StarkProof::new([1u8; 32], large_data.clone(), vec![], vec![], vec![]);

        let serialized = proof.serialize();
        let deserialized = StarkProof::deserialize(&serialized).unwrap();

        assert_eq!(deserialized.inputs, large_data);
    }

    #[test]
    fn test_stark_proof_deserialize_too_short() {
        let data = [1u8; 10]; // Too short
        let result = StarkProof::deserialize(&data);

        assert!(result.is_err());
        match result {
            Err(SerializationError::DataTooShort) => {}
            _ => panic!("Expected DataTooShort error"),
        }
    }

    #[test]
    fn test_stark_proof_deserialize_invalid_length() {
        let mut data = vec![0u8; 100];
        // Set an impossibly large inputs_len
        data[32] = 0xFF;
        data[33] = 0xFF;
        data[34] = 0xFF;
        data[35] = 0xFF;

        let result = StarkProof::deserialize(&data);
        assert!(result.is_err());
    }

    #[test]
    fn test_stark_proof_serialized_size() {
        let proof = StarkProof::new(
            [1u8; 32],
            vec![1; 100],
            vec![2; 200],
            vec![3; 300],
            vec![4; 400],
        );

        let expected_size = 32 + 4 + 100 + 4 + 200 + 4 + 300 + 4 + 400;
        assert_eq!(proof.serialized_size(), expected_size);
        assert_eq!(proof.serialize().len(), expected_size);
    }

    #[test]
    fn test_proof_validation_error_display() {
        let err = ProofValidationError::InputsTooLarge(20000);
        let display = format!("{}", err);
        assert!(display.contains("Inputs too large"));
        assert!(display.contains("20000"));
    }

    #[test]
    fn test_serialization_error_display() {
        let err = SerializationError::InvalidFormat("test".to_string());
        let display = format!("{}", err);
        assert!(display.contains("Invalid format"));
        assert!(display.contains("test"));
    }

    #[test]
    fn test_constants() {
        assert_eq!(MAX_PROOF_SIZE, 500 * 1024);
        assert_eq!(MAX_PUBLIC_INPUTS_SIZE, 100 * 1024);
        assert_eq!(MAX_INPUTS_SIZE, 10 * 1024);
        assert_eq!(MAX_OUTPUTS_SIZE, 10 * 1024);
    }
}
